In [78]:
import numpy

In [79]:
def ones(*shape):
    return numpy.ones(shape, dtype=numpy.float32)

In [80]:
a = ones(2, 3)
a  # print(repr(a))

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [81]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [82]:
"""
Задача: 
вывести красиво операцию A + B = C на экран
"""
my_input = [ones(2, 3), '+', ones(2, 3), '=', ones(2,3)*2]
print(my_input)

[array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32), '+', array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32), '=', array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)]


In [83]:
lines = [str(x).split('\n') for x in my_input]; lines

[['[[1. 1. 1.]', ' [1. 1. 1.]]'],
 ['+'],
 ['[[1. 1. 1.]', ' [1. 1. 1.]]'],
 ['='],
 ['[[2. 2. 2.]', ' [2. 2. 2.]]']]

In [84]:
a = numpy.arange(1, 7).reshape(2, -1); print(a)

[[1 2 3]
 [4 5 6]]


In [85]:
rows = str(a).split('\n'); rows

['[[1 2 3]', ' [4 5 6]]']

In [86]:
width = len(rows[-1]); width

9

In [87]:
empty_row = ' ' * width

In [88]:
rows = [row.ljust(width) for row in rows]; rows

['[[1 2 3] ', ' [4 5 6]]']

In [89]:
max_rows = 3

In [90]:
rows.extend([empty_row] * (max_rows - len(rows))); rows

['[[1 2 3] ', ' [4 5 6]]', '         ']

In [91]:
print('\n'.join(rows))

[[1 2 3] 
 [4 5 6]]
         


In [92]:
def add_spaces(rows, max_rows):
    
    width = len(rows[-1])
    empty_rows = [' ' * width for _ in range(max_rows - len(rows))]
    
    rows = [row.ljust(width) for row in rows]
    rows.extend(empty_rows)
    
    return rows


rows = str(a).split('\n')
print('\n'.join(add_spaces(rows, max_rows=4)))

[[1 2 3] 
 [4 5 6]]
         
         


In [100]:
def pp(*lst):
    lines = [str(x).split('\n') for x in lst]
    max_rows = max(map(len, lines))
    
    formatted_lines = [add_spaces(rows, max_rows=max_rows) for rows in lines]
#     arr = numpy.array(formatted_lines).T
#     print('\n'.join(' '.join(line) for line in arr))
    print('\n'.join(' '.join(line) for line in zip(*formatted_lines)))

In [101]:
pp(*my_input)

[[1. 1. 1.]  + [[1. 1. 1.]  = [[2. 2. 2.] 
 [1. 1. 1.]]    [1. 1. 1.]]    [2. 2. 2.]]


In [103]:
A = numpy.arange(1, 11).reshape(5, 2)
B = numpy.linspace(10, 30, 10).reshape(5, 2)
R = A * B
pp(A, '*', B, '=', R)

[[ 1  2]  * [[10.         12.22222222]  = [[ 10.          24.44444444] 
 [ 3  4]     [14.44444444 16.66666667]     [ 43.33333333  66.66666667] 
 [ 5  6]     [18.88888889 21.11111111]     [ 94.44444444 126.66666667] 
 [ 7  8]     [23.33333333 25.55555556]     [163.33333333 204.44444444] 
 [ 9 10]]    [27.77777778 30.        ]]    [250.         300.        ]]


In [104]:
class Op:
    def __init__(self, name, func):
        self.name = name
        self.func = func
    
    def __call__(self, x, y):
        r = self.func(x, y)
        pp(x, self.name, y, '=', r)

SSum = Op('+', lambda x, y: x + y)
SMul = Op('*', lambda x, y: x * y)
MMul = Op('@', lambda x, y: x @ y)  # python 3.5+ 

SMul(A, B)

[[ 1  2]  * [[10.         12.22222222]  = [[ 10.          24.44444444] 
 [ 3  4]     [14.44444444 16.66666667]     [ 43.33333333  66.66666667] 
 [ 5  6]     [18.88888889 21.11111111]     [ 94.44444444 126.66666667] 
 [ 7  8]     [23.33333333 25.55555556]     [163.33333333 204.44444444] 
 [ 9 10]]    [27.77777778 30.        ]]    [250.         300.        ]]


In [105]:
MMul(A.T, B)

[[ 1  3  5  7  9]  @ [[10.         12.22222222]  = [[561.11111111 616.66666667] 
 [ 2  4  6  8 10]]    [14.44444444 16.66666667]     [655.55555556 722.22222222]]
                      [18.88888889 21.11111111]                                 
                      [23.33333333 25.55555556]                                 
                      [27.77777778 30.        ]]                                
