# Массивы

In [26]:
import numpy

In [27]:
a = numpy.zeros((2, 3), dtype=numpy.float32)  # ничего не вывело

In [28]:
a  # выведет а, по оси Y левая координата (внешняя), по оси X правая (внутренняя) 

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [29]:
a;  # не выведет а

In [30]:
type(a)

numpy.ndarray

In [31]:
a.__class__

numpy.ndarray

In [32]:
a = numpy.zeros((2, 3, 4), dtype=numpy.float32); a  # выведет новый а, по оси X правая координата, по оси Y -- внешние координаты

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [33]:
a += 1; display(a); a *= 2; display(a);  # сложение со скаляром, умножение на скаляр; display -- вывод с помощью jupyter (colab)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]], dtype=float32)

In [34]:
def ones(*shape):
    return numpy.ones(shape, dtype=numpy.float32)

In [35]:
ones(2, 3)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

# Задача

In [36]:
"""
Задача: 
вывести красиво операцию A + B = C на экран
"""
my_input = [ones(2, 3), '+', ones(2, 3), '=', ones(2,3)*2]
print(my_input)
print(*my_input)
display(*my_input)

[array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32), '+', array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32), '=', array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)]
[[1. 1. 1.]
 [1. 1. 1.]] + [[1. 1. 1.]
 [1. 1. 1.]] = [[2. 2. 2.]
 [2. 2. 2.]]


array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

'+'

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

'='

array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)

In [37]:
# пусть наша функция имеет такой формат:
def pp(*lst):
    pass
pp(*my_input)

In [38]:
m = ones(2, 3)
print(repr(m))

print(f"{'-'*40:\n^42}")

for element in repr(m).split('\n'):
      print(repr(element))

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

----------------------------------------

'array([[1., 1., 1.],'
'       [1., 1., 1.]], dtype=float32)'


In [39]:
lines = [repr(a).split('\n') for a in my_input]; lines

[['array([[1., 1., 1.],', '       [1., 1., 1.]], dtype=float32)'],
 ["'+'"],
 ['array([[1., 1., 1.],', '       [1., 1., 1.]], dtype=float32)'],
 ["'='"],
 ['array([[2., 2., 2.],', '       [2., 2., 2.]], dtype=float32)']]

In [40]:
print(m)

[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
lines = [str(a).split('\n') for a in my_input]; lines

[['[[1. 1. 1.]', ' [1. 1. 1.]]'],
 ['+'],
 ['[[1. 1. 1.]', ' [1. 1. 1.]]'],
 ['='],
 ['[[2. 2. 2.]', ' [2. 2. 2.]]']]

In [42]:
max_lines = max([len(line) for line in lines])
max_lines

2

In [43]:
lines = [line + ['']*(max_lines-len(line)) for line in lines]; lines

[['[[1. 1. 1.]', ' [1. 1. 1.]]'],
 ['+', ''],
 ['[[1. 1. 1.]', ' [1. 1. 1.]]'],
 ['=', ''],
 ['[[2. 2. 2.]', ' [2. 2. 2.]]']]

### транспонирование, reshape, операция получения максимума

In [44]:
lines_arr = numpy.array(lines); lines_arr.T

array([['[[1. 1. 1.]', '+', '[[1. 1. 1.]', '=', '[[2. 2. 2.]'],
       [' [1. 1. 1.]]', '', ' [1. 1. 1.]]', '', ' [2. 2. 2.]]']],
      dtype='<U12')

In [45]:
widths = [len(x) for x in lines]; display(widths)

[2, 2, 2, 2, 2]

In [46]:
lines_arr.flatten()

array(['[[1. 1. 1.]', ' [1. 1. 1.]]', '+', '', '[[1. 1. 1.]',
       ' [1. 1. 1.]]', '=', '', '[[2. 2. 2.]', ' [2. 2. 2.]]'],
      dtype='<U12')

In [47]:
widths = numpy.array([len(x) for x in lines_arr.flatten()]); display(widths)
widths = widths.reshape(len(lines_arr), -1); display(widths)

array([11, 12,  1,  0, 11, 12,  1,  0, 11, 12])

array([[11, 12],
       [ 1,  0],
       [11, 12],
       [ 1,  0],
       [11, 12]])

In [48]:
widths = widths.reshape(*lines_arr.shape); display(widths)

array([[11, 12],
       [ 1,  0],
       [11, 12],
       [ 1,  0],
       [11, 12]])

In [49]:
numpy.max(widths)

12

In [50]:
widths

array([[11, 12],
       [ 1,  0],
       [11, 12],
       [ 1,  0],
       [11, 12]])

In [51]:
widths.max()

12

In [52]:
widths.max(axis=1)  # складывает по внутренней оси, 

array([12,  1, 12,  1, 12])

In [53]:
line_widths = widths.max(axis=1)

### форматирование всё равно придётся делать поэлементно. зашли в тупик...

In [54]:
lines = [str(a).split('\n') for a in my_input]; lines
max_lines = max([len(line) for line in lines])
max_lines

2

In [55]:
def fmt_item(lines, max_lines=0):
    max_width = max([len(line) for line in lines])
    empty = ' '*max_width
    lines = [line.ljust(max_width) for line in lines]
    lines += [empty] * (max_lines - len(lines))
    return lines    
    
results = fmt_item(str(numpy.arange(1, 5).reshape(2,-1)).split('\n'), max_lines=3)
print('\n'.join(results))

[[1 2] 
 [3 4]]
       


In [56]:
# а что делать дальше, когда у нас есть такие массивы? 
# воспользуемся array().T

In [57]:
def pp(*lst):
    lines = [str(item).split('\n') for item in lst]
    max_lines = max([len(item) for item in lines])
    lines = [fmt_item(item, max_lines=max_lines) for item in lines]
    lines_t = numpy.array(lines).T
    print('\n'.join([' '.join(line) for line in lines_t]))
    
pp(*my_input)


[[1. 1. 1.]  + [[1. 1. 1.]  = [[2. 2. 2.] 
 [1. 1. 1.]]    [1. 1. 1.]]    [2. 2. 2.]]


### Попробуем нашу функцию:

In [58]:
A = numpy.arange(1, 11).reshape(5,2)
B = numpy.linspace(10, 30, 10).reshape(5,2)
R = A * B
pp(A, '*', B, '=', R)

[[ 1  2]  * [[10.         12.22222222]  = [[ 10.          24.44444444] 
 [ 3  4]     [14.44444444 16.66666667]     [ 43.33333333  66.66666667] 
 [ 5  6]     [18.88888889 21.11111111]     [ 94.44444444 126.66666667] 
 [ 7  8]     [23.33333333 25.55555556]     [163.33333333 204.44444444] 
 [ 9 10]]    [27.77777778 30.        ]]    [250.         300.        ]]


In [59]:
import operator
#operator.add = lambda x, y: x + y

def op(x, name, y, func):
    r = func(x, y)
    pp(x, name, y, '=', r)
    
op(numpy.array([[1,2],[3,4]]), '+', numpy.array([[5,6],[7,8]]), operator.add)

[[1 2]  + [[5 6]  = [[ 6  8] 
 [3 4]]    [7 8]]    [10 12]]


In [60]:
# вспомним классы, оформим в виде класса
class Op:
    def __init__(self, name, func):
        self.name = name
        self.func = func
    
    def __call__(self, x, y):
        r = self.func(x, y)
        pp(x, self.name, y, '=', r)

SSum = Op('+', lambda x, y: x + y)
SMul = Op('*', lambda x, y: x * y)
MMul = Op('@', lambda x, y: x @ y)  # python 3.5+ 

SMul(A, B)

[[ 1  2]  * [[10.         12.22222222]  = [[ 10.          24.44444444] 
 [ 3  4]     [14.44444444 16.66666667]     [ 43.33333333  66.66666667] 
 [ 5  6]     [18.88888889 21.11111111]     [ 94.44444444 126.66666667] 
 [ 7  8]     [23.33333333 25.55555556]     [163.33333333 204.44444444] 
 [ 9 10]]    [27.77777778 30.        ]]    [250.         300.        ]]


In [61]:
MMul(A.T, B)

[[ 1  3  5  7  9]  @ [[10.         12.22222222]  = [[561.11111111 616.66666667] 
 [ 2  4  6  8 10]]    [14.44444444 16.66666667]     [655.55555556 722.22222222]]
                      [18.88888889 21.11111111]                                 
                      [23.33333333 25.55555556]                                 
                      [27.77777778 30.        ]]                                


# Простая индексация

In [64]:
pp(B[0, :1], B[-1,-2], B[-2:-1, 0])

[10.] 27.77777777777778 [23.33333333]


# Broadcasting и stack

In [0]:
SSum(A, B[0])  # что произойдёт? это преобразование называется broadcasting

In [0]:
SMul(A, B[0])  # смотрим ещё раз, на умножении

In [0]:
SMul(A, numpy.stack(list(B[0:1])*5))

# Бинарные и логические операции с массивами

In [0]:
pp(A, A>3, B, B>=10.) # сравнение float -- дело неточное

In [0]:
1<<23

Float 32 format: ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Float_example.svg/1180px-Float_example.svg.png) 

In [0]:
pp(numpy.isclose(B, 10), (10 - 1e-7 <= B) & (B <= 10 + 1e-7))

In [0]:
idx = numpy.isclose(B, 10) | numpy.isclose(B, 30)
B[idx]

# Индексация массивов

In [0]:
pp(B)
pp(numpy.isclose(B[1:-1, 1:-1], 10))  # классическая индексация питона
pp(numpy.isclose(B[0], 10))   # берём первую строку
pp(numpy.isclose(B[:, 1], 10))   # берём второй столбец

# Cлучайные значения

In [0]:
pp(numpy.random.uniform(0, 1), numpy.random.randn(2, 3), numpy.random.rand(2, 3))

In [0]:
import random
random.seed(10)
numpy.random.seed(10)
nr = numpy.random.uniform(0, 1)
nr2 = numpy.random.uniform(0, 1)
rr = random.uniform(0, 1)
rr2 = random.uniform(0, 1)
pp(rr, nr, rr2, nr2)

random.seed(10)
numpy.random.seed(10)
rr = random.uniform(0, 1)
nr = numpy.random.uniform(0, 1)
rr2 = random.uniform(0, 1)
nr2 = numpy.random.uniform(0, 1)
pp(rr, nr, rr2, nr2)

In [0]:
import matplotlib
# значение по умолчанию в colab, но не в локальных ноутбуках
matplotlib.rcParams['axes.grid'] = True

import matplotlib.pyplot as plt
# нарисуем график для 11 случайных нормально распределённых чисел.
x = numpy.linspace(0, 10, 11)
dots = numpy.random.randn(11)
plt.plot(x, dots);

In [0]:
import matplotlib
matplotlib.rcParams['axes.grid'] = False  # убираем белую клетку (настройки colab)

import matplotlib.pyplot as plt
plt.plot(x, dots);  # рисуем линию ещё раз

In [0]:
# если надо просто вывести точки, без линий между ними
plt.scatter(x, dots);

In [0]:
# выводим двумерный массив, используя цветовую схему 'hot'.
# matplotlib автоматически определяет минимум и максимум
# по нему настраивает цвета
plt.imshow(numpy.arange(0, 120).reshape(6, 20), 'hot');

# Строки и словари

In [0]:
# Задача: определить, какой символ встречается чаще всего в данном тексте,
# не считая пробелов!
a = "Кот сидел на крыше тише мыши"
pp(set(list(a)))

In [0]:
from collections import Counter
# приближённое решение.
Counter(list(a)).most_common()
# убрать пробел и будет то, что надо. попробуйте сами.

In [0]:
# напишем вручную код аналогичный тому, что происходит внутри Counter
counter = {}
for ch in list(a.lower()):
    if ch == ' ': continue
    if ch in counter:
        counter[ch] += 1
    else:
        counter[ch] = 1
    
pp(counter)

In [0]:
pp(type(ch))  # в питоне даже отдельные символы -- это строчки

In [0]:
max(counter.values())  # нашли максимум

In [0]:
# алгоритм для поиска максимума
winner_ch = None
winner_count = 0
for ch, count in counter.items():
  if count > winner_count:
      winner_count = count
      winner_ch = ch
print(winner_ch, winner_count)  # и вот наш символ-победитель
# имейте в виду, победителя на самом деле три.
# исправьте код, чтобы вывести и второй и третий.

 ---

---

---

In [0]:
A

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [0]:
a=A[0]
b=B[0]
c=B[0].T
print(a.shape, b.shape, c.shape)
pp(a, ' ', b, ' ', a+b)

(2,) (2,) (2,)
[1 2]   [10.         12.22222222]   [11.         14.22222222]


In [0]:
a=A[0:1]
b=B[0:1]
c=B[0:1].T
pp('shapes:', a.shape, b.shape, c.shape)
pp('arrays:', a, ' ', c, ' ', a+c)

shapes: (1, 2) (1, 2) (2, 1)
arrays: [[1 2]]   [[10.        ]    [[11.         12.        ] 
                   [12.22222222]]    [13.22222222 14.22222222]]


In [0]:
a = A[0]
b = A[0].reshape(-1, 1)
c = A[0][:,None] # or [:, numpy.newaxis]
d = A[0][None, :] # or [numpy.newaxis, :]
pp(a.shape, ' ', b.shape, ' ', c.shape, ' ', d.shape)
print()
pp(a, ' ', b, ' ', c, ' ', d)

(2,)   (2, 1)   (2, 1)   (1, 2)

[1 2]   [[1]    [[1]    [[1 2]]
         [2]]    [2]]          
