In [1]:
import numpy as np

In [2]:
def ReLU(x):
    return x if x > 0 else 0

In [21]:
X = np.array([[-1, 0.1, 1], [2, 0, -2]])

In [6]:
np.vectorize(ReLU)(X)

array([[0, 0, 1],
       [2, 0, 0]])

In [11]:
a = np.array([[1, 2, 3]])
batch_size = 5
np.vstack((a,)*5)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [3]:
np.arange(1, 7).reshape(2, 3) + np.array([1, 2, 3])

array([[2, 4, 6],
       [5, 7, 9]])

In [3]:
a = np.array([3, 2, 1, 0])
b = np.array([5, 5, 1, 5])

In [5]:
5e-1

0.5

In [22]:
(X + np.abs(X)) / 2

array([[0. , 0.1, 1. ],
       [2. , 0. , 0. ]])

In [23]:
X[X < 0] = 0
print(X)

[[0.  0.1 1. ]
 [2.  0.  0. ]]


In [12]:
q = np.arange(1, 7).reshape(2, 3)
print(q)

[[1 2 3]
 [4 5 6]]


In [14]:
np.mean(q, axis=0)

array([2.5, 3.5, 4.5])

In [15]:
a = [[1, 2, 3]]
b = 5 * np.random.randn(3, 3)
print(b)

[[-1.3370127  -7.02710123 -9.15022806]
 [ 0.01178805  1.14885011  0.01161706]
 [ 4.76006304  4.71626139 -6.78393815]]


In [16]:
np.mean(a - b, axis=0)

array([-0.14494613,  2.38732991,  8.30751638])

In [17]:
a - np.mean(b, axis=0)

array([[-0.14494613,  2.38732991,  8.30751638]])

In [4]:
y = np.array([1, 2, 3, 3, 2, 1])
y[y == 3] = 0
y

array([1, 2, 0, 0, 2, 1])

In [5]:
class Foo:
    bar = True
    
    def hmm():
        return 'hmm'

In [16]:
a = Foo()
a.che = 'hui'
dir(a)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'bar',
 'che',
 'hmm']

In [18]:
a = np.array([-1.5, 1.5, 2.9])
np.floor(a)

array([-2.,  1.,  2.])

In [19]:
np.array([1, 2, 3]) == np.array([3, 2, 1])

array([False,  True, False])