In [1]:
import numpy as np

In [2]:
def ReLU(x):
    return x if x > 0 else 0

In [5]:
X = np.array([[-1, 0.1, 1], [2, 0, -2]])

In [6]:
np.vectorize(ReLU)(X)

array([[0, 0, 1],
       [2, 0, 0]])

In [11]:
a = np.array([[1, 2, 3]])
batch_size = 5
np.vstack((a,)*5)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [3]:
np.arange(1, 7).reshape(2, 3) + np.array([1, 2, 3])

array([[2, 4, 6],
       [5, 7, 9]])

In [3]:
a = np.array([3, 2, 1, 0])
b = np.array([5, 5, 1, 5])

In [5]:
5e-1

0.5

In [7]:
(X + np.abs(X)) / 2

array([[0. , 0.1, 1. ],
       [2. , 0. , 0. ]])

In [12]:
q = np.arange(1, 7).reshape(2, 3)
print(q)

[[1 2 3]
 [4 5 6]]


In [14]:
np.mean(q, axis=0)

array([2.5, 3.5, 4.5])

In [15]:
a = [[1, 2, 3]]
b = 5 * np.random.randn(3, 3)
print(b)

[[-1.3370127  -7.02710123 -9.15022806]
 [ 0.01178805  1.14885011  0.01161706]
 [ 4.76006304  4.71626139 -6.78393815]]


In [16]:
np.mean(a - b, axis=0)

array([-0.14494613,  2.38732991,  8.30751638])

In [17]:
a - np.mean(b, axis=0)

array([[-0.14494613,  2.38732991,  8.30751638]])