In [84]:
import numpy as np

In [121]:
train = np.random.rand(4, 5)
test = np.random.rand(2, 5)
print(train)
print()
print(test)

[[0.57989196 0.12389033 0.77831536 0.45868946 0.37524073]
 [0.20021226 0.70298835 0.34133481 0.53704633 0.50077212]
 [0.44741635 0.53090134 0.14273386 0.11589044 0.11523288]
 [0.18605744 0.76271566 0.57896134 0.6820892  0.29031305]]

[[0.23697393 0.41035266 0.49075801 0.83521156 0.43727169]
 [0.97675523 0.96340123 0.4354508  0.87723391 0.82885805]]


In [122]:
np.split(train, 2)

[array([[0.57989196, 0.12389033, 0.77831536, 0.45868946, 0.37524073],
        [0.20021226, 0.70298835, 0.34133481, 0.53704633, 0.50077212]]),
 array([[0.44741635, 0.53090134, 0.14273386, 0.11589044, 0.11523288],
        [0.18605744, 0.76271566, 0.57896134, 0.6820892 , 0.29031305]])]

In [123]:
np.concatenate(np.split(train, 2))

array([[0.57989196, 0.12389033, 0.77831536, 0.45868946, 0.37524073],
       [0.20021226, 0.70298835, 0.34133481, 0.53704633, 0.50077212],
       [0.44741635, 0.53090134, 0.14273386, 0.11589044, 0.11523288],
       [0.18605744, 0.76271566, 0.57896134, 0.6820892 , 0.29031305]])

## numpy.newaxis

In [116]:
a = np.arange(1, 7).reshape(2, 3)
print(a)
print()
print(a[None])
print()
print(a[:, None])
print()
print(a[:, :, None])

[[1 2 3]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]]]

[[[1 2 3]]

 [[4 5 6]]]

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [88]:
print(train[None, :])
print(train[None, :].shape)

[[[0.81622821 0.01879675 0.08826012 0.75907173 0.8403613 ]
  [0.42300417 0.43102753 0.060075   0.03514232 0.72101323]
  [0.53652733 0.31415885 0.74371171 0.02604738 0.95709338]
  [0.92306372 0.33426721 0.18494244 0.31318186 0.00737051]]]
(1, 4, 5)


In [89]:
print(test[:, None, :])
print(test[:, None, :].shape)

[[[0.2764002  0.58861816 0.15376402 0.28711623 0.06069288]]

 [[0.37552268 0.75560122 0.76469948 0.98785819 0.38164379]]]
(2, 1, 5)


In [90]:
print(abs(train[None, :] - test[:, None, :]))

[[[0.53982801 0.56982141 0.0655039  0.47195551 0.77966842]
  [0.14660397 0.15759063 0.09368903 0.25197391 0.66032035]
  [0.26012712 0.2744593  0.58994768 0.26106885 0.89640049]
  [0.64666352 0.25435095 0.03117842 0.02606563 0.05332237]]

 [[0.44070552 0.73680446 0.67643936 0.22878646 0.45871751]
  [0.04748148 0.32457368 0.70462449 0.95271587 0.33936944]
  [0.16100464 0.44144236 0.02098778 0.96181081 0.57544959]
  [0.54754104 0.42133401 0.57975704 0.67467633 0.37427328]]]


In [91]:
sum(map(float, '0.60395976 0.20385342 0.20566971 0.02415189 0.01458161'.split()))

1.05221639

In [92]:
np.abs(train[None, :] - test[:, None, :]).sum(axis=2)

array([[2.42677723, 1.31017787, 2.28200345, 1.01158089],
       [2.54145331, 2.36876496, 2.16069517, 2.5975817 ]])

In [93]:
train = train.reshape(1, -1)
test = test.reshape(-1, 1)

In [94]:
print(train[:5])
print()
print(test[:,:5])

[[0.81622821 0.01879675 0.08826012 0.75907173 0.8403613  0.42300417
  0.43102753 0.060075   0.03514232 0.72101323 0.53652733 0.31415885
  0.74371171 0.02604738 0.95709338 0.92306372 0.33426721 0.18494244
  0.31318186 0.00737051]]

[[0.2764002 ]
 [0.58861816]
 [0.15376402]
 [0.28711623]
 [0.06069288]
 [0.37552268]
 [0.75560122]
 [0.76469948]
 [0.98785819]
 [0.38164379]]


In [95]:
print(abs(test - train))

[[5.39828006e-01 2.57603450e-01 1.88140077e-01 4.82671532e-01
  5.63961094e-01 1.46603966e-01 1.54627328e-01 2.16325204e-01
  2.41257882e-01 4.44613024e-01 2.60127123e-01 3.77586528e-02
  4.67311506e-01 2.50352822e-01 6.80693174e-01 6.46663522e-01
  5.78670036e-02 9.14577600e-02 3.67816554e-02 2.69029690e-01]
 [2.27610050e-01 5.69821407e-01 5.00358034e-01 1.70453576e-01
  2.51743138e-01 1.65613991e-01 1.57590628e-01 5.28543161e-01
  5.53475838e-01 1.32395068e-01 5.20908335e-02 2.74459304e-01
  1.55093549e-01 5.62570779e-01 3.68475218e-01 3.34445566e-01
  2.54350953e-01 4.03675716e-01 2.75436301e-01 5.81247646e-01]
 [6.62464184e-01 1.34967273e-01 6.55038998e-02 6.05307710e-01
  6.86597272e-01 2.69240143e-01 2.77263506e-01 9.36890268e-02
  1.18621705e-01 5.67249202e-01 3.82763300e-01 1.60394830e-01
  5.89947683e-01 1.27716645e-01 8.03329352e-01 7.69299700e-01
  1.80503181e-01 3.11784176e-02 1.59417833e-01 1.46393512e-01]
 [5.29111980e-01 2.68319477e-01 1.98856104e-01 4.71955505e-01
  5.5

In [96]:
x = abs(test - train)[:5,:5]; x

array([[0.53982801, 0.25760345, 0.18814008, 0.48267153, 0.56396109],
       [0.22761005, 0.56982141, 0.50035803, 0.17045358, 0.25174314],
       [0.66246418, 0.13496727, 0.0655039 , 0.60530771, 0.68659727],
       [0.52911198, 0.26831948, 0.1988561 , 0.47195551, 0.55324507],
       [0.75553533, 0.04189613, 0.02756724, 0.69837885, 0.77966842]])

In [97]:
np.trace(x)

2.4267772335086666

In [98]:
print(np.trace(abs(test - train)))

4.795542194794966


In [99]:
y = abs(test - train).reshape(2, 5, 4, 5); print(y)

[[[[5.39828006e-01 2.57603450e-01 1.88140077e-01 4.82671532e-01
    5.63961094e-01]
   [1.46603966e-01 1.54627328e-01 2.16325204e-01 2.41257882e-01
    4.44613024e-01]
   [2.60127123e-01 3.77586528e-02 4.67311506e-01 2.50352822e-01
    6.80693174e-01]
   [6.46663522e-01 5.78670036e-02 9.14577600e-02 3.67816554e-02
    2.69029690e-01]]

  [[2.27610050e-01 5.69821407e-01 5.00358034e-01 1.70453576e-01
    2.51743138e-01]
   [1.65613991e-01 1.57590628e-01 5.28543161e-01 5.53475838e-01
    1.32395068e-01]
   [5.20908335e-02 2.74459304e-01 1.55093549e-01 5.62570779e-01
    3.68475218e-01]
   [3.34445566e-01 2.54350953e-01 4.03675716e-01 2.75436301e-01
    5.81247646e-01]]

  [[6.62464184e-01 1.34967273e-01 6.55038998e-02 6.05307710e-01
    6.86597272e-01]
   [2.69240143e-01 2.77263506e-01 9.36890268e-02 1.18621705e-01
    5.67249202e-01]
   [3.82763300e-01 1.60394830e-01 5.89947683e-01 1.27716645e-01
    8.03329352e-01]
   [7.69299700e-01 1.80503181e-01 3.11784176e-02 1.59417833e-01
    1.46

In [100]:
np.trace(y, axis1=1, axis2=3)

array([[2.42677723, 1.31017787, 2.28200345, 1.01158089],
       [2.54145331, 2.36876496, 2.16069517, 2.5975817 ]])

In [101]:
a = abs(test - train)[:5,:5]
print(a)
print(np.trace(a))

[[0.53982801 0.25760345 0.18814008 0.48267153 0.56396109]
 [0.22761005 0.56982141 0.50035803 0.17045358 0.25174314]
 [0.66246418 0.13496727 0.0655039  0.60530771 0.68659727]
 [0.52911198 0.26831948 0.1988561  0.47195551 0.55324507]
 [0.75553533 0.04189613 0.02756724 0.69837885 0.77966842]]
2.4267772335086666


In [102]:
A = np.arange(1, 17).reshape(4, -1)

In [103]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [104]:
np.hsplit(A, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [105]:
x = abs(test - train)
np.hsplit(x, 2)

[array([[5.39828006e-01, 2.57603450e-01, 1.88140077e-01, 4.82671532e-01,
         5.63961094e-01, 1.46603966e-01, 1.54627328e-01, 2.16325204e-01,
         2.41257882e-01, 4.44613024e-01],
        [2.27610050e-01, 5.69821407e-01, 5.00358034e-01, 1.70453576e-01,
         2.51743138e-01, 1.65613991e-01, 1.57590628e-01, 5.28543161e-01,
         5.53475838e-01, 1.32395068e-01],
        [6.62464184e-01, 1.34967273e-01, 6.55038998e-02, 6.05307710e-01,
         6.86597272e-01, 2.69240143e-01, 2.77263506e-01, 9.36890268e-02,
         1.18621705e-01, 5.67249202e-01],
        [5.29111980e-01, 2.68319477e-01, 1.98856104e-01, 4.71955505e-01,
         5.53245067e-01, 1.35887939e-01, 1.43911301e-01, 2.27041231e-01,
         2.51973909e-01, 4.33896998e-01],
        [7.55535327e-01, 4.18961297e-02, 2.75672435e-02, 6.98378853e-01,
         7.79668415e-01, 3.62311286e-01, 3.70334649e-01, 6.17883579e-04,
         2.55505613e-02, 6.60320345e-01],
        [4.40705525e-01, 3.56725932e-01, 2.87262559e-01, 3.8

In [106]:
np.trace(x)

4.795542194794966

In [107]:
a = np.array([2, 3, 4, 1, 5])
i = np.argsort(a)[0]
a[i]

1

## numpy masks

In [112]:
a = np.arange(1, 7).reshape(2, 3)
mask = a > 3
print(a)
print()
print(mask)

[[1 2 3]
 [4 5 6]]

[[False False False]
 [ True  True  True]]


In [115]:
a[mask]

array([4, 5, 6])