In [3]:
import numpy as np

In [4]:
train = np.random.rand(4, 5)
test = np.random.rand(2, 5)
print(train)
print()
print(test)

[[0.99293655 0.31941918 0.65055556 0.95603659 0.68770326]
 [0.82945106 0.02080597 0.47584818 0.63739184 0.20363312]
 [0.74380875 0.50072515 0.20724354 0.63575644 0.82741106]
 [0.05614926 0.74708535 0.08138273 0.14493916 0.95598931]]

[[0.9895959  0.47191409 0.07417317 0.89314452 0.11053934]
 [0.60400857 0.59294113 0.69302763 0.46723605 0.27907906]]


In [5]:
np.split(train, 2)

[array([[0.99293655, 0.31941918, 0.65055556, 0.95603659, 0.68770326],
        [0.82945106, 0.02080597, 0.47584818, 0.63739184, 0.20363312]]),
 array([[0.74380875, 0.50072515, 0.20724354, 0.63575644, 0.82741106],
        [0.05614926, 0.74708535, 0.08138273, 0.14493916, 0.95598931]])]

In [6]:
np.concatenate(np.split(train, 2))

array([[0.99293655, 0.31941918, 0.65055556, 0.95603659, 0.68770326],
       [0.82945106, 0.02080597, 0.47584818, 0.63739184, 0.20363312],
       [0.74380875, 0.50072515, 0.20724354, 0.63575644, 0.82741106],
       [0.05614926, 0.74708535, 0.08138273, 0.14493916, 0.95598931]])

## numpy.newaxis

In [7]:
a = np.arange(1, 7).reshape(2, 3)
print(a)
print()
print(a[None])
print()
print(a[:, None])
print()
print(a[:, :, None])

[[1 2 3]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]]]

[[[1 2 3]]

 [[4 5 6]]]

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [8]:
print(train[None, :])
print(train[None, :].shape)

[[[0.99293655 0.31941918 0.65055556 0.95603659 0.68770326]
  [0.82945106 0.02080597 0.47584818 0.63739184 0.20363312]
  [0.74380875 0.50072515 0.20724354 0.63575644 0.82741106]
  [0.05614926 0.74708535 0.08138273 0.14493916 0.95598931]]]
(1, 4, 5)


In [9]:
print(test[:, None, :])
print(test[:, None, :].shape)

[[[0.9895959  0.47191409 0.07417317 0.89314452 0.11053934]]

 [[0.60400857 0.59294113 0.69302763 0.46723605 0.27907906]]]
(2, 1, 5)


In [10]:
print(abs(train[None, :] - test[:, None, :]))

[[[0.00334066 0.15249491 0.57638239 0.06289207 0.57716392]
  [0.16014483 0.45110812 0.40167501 0.25575268 0.09309379]
  [0.24578715 0.02881106 0.13307037 0.25738808 0.71687172]
  [0.93344664 0.27517126 0.00720956 0.74820536 0.84544998]]

 [[0.38892798 0.27352195 0.04247207 0.48880055 0.4086242 ]
  [0.22544249 0.57213516 0.21717945 0.17015579 0.07544594]
  [0.13980018 0.09221598 0.48578409 0.16852039 0.548332  ]
  [0.54785931 0.15414422 0.6116449  0.32229689 0.67691025]]]


In [11]:
sum(map(float, '0.60395976 0.20385342 0.20566971 0.02415189 0.01458161'.split()))

1.05221639

In [12]:
np.abs(train[None, :] - test[:, None, :]).sum(axis=2)

array([[1.37227396, 1.36177444, 1.38192838, 2.80948279],
       [1.60234675, 1.26035883, 1.43465263, 2.31285557]])

In [13]:
train = train.reshape(1, -1)
test = test.reshape(-1, 1)

In [14]:
print(train[:5])
print()
print(test[:,:5])

[[0.99293655 0.31941918 0.65055556 0.95603659 0.68770326 0.82945106
  0.02080597 0.47584818 0.63739184 0.20363312 0.74380875 0.50072515
  0.20724354 0.63575644 0.82741106 0.05614926 0.74708535 0.08138273
  0.14493916 0.95598931]]

[[0.9895959 ]
 [0.47191409]
 [0.07417317]
 [0.89314452]
 [0.11053934]
 [0.60400857]
 [0.59294113]
 [0.69302763]
 [0.46723605]
 [0.27907906]]


In [15]:
print(abs(test - train))

[[0.00334066 0.67017672 0.33904034 0.0335593  0.30189264 0.16014483
  0.96878993 0.51374772 0.35220406 0.78596277 0.24578715 0.48887075
  0.78235236 0.35383946 0.16218484 0.93344664 0.24251055 0.90821317
  0.84465674 0.03360659]
 [0.52102246 0.15249491 0.17864147 0.4841225  0.21578917 0.35753697
  0.45110812 0.00393409 0.16547774 0.26828097 0.27189465 0.02881106
  0.26467055 0.16384234 0.35549696 0.41576483 0.27517126 0.39053136
  0.32697493 0.48407522]
 [0.91876338 0.24524601 0.57638239 0.88186342 0.61353009 0.75527789
  0.0533672  0.40167501 0.56321867 0.12945995 0.66963558 0.42655198
  0.13307037 0.56158327 0.75323789 0.01802391 0.67291218 0.00720956
  0.07076599 0.88181614]
 [0.09979203 0.57372534 0.24258896 0.06289207 0.20544126 0.06369346
  0.87233855 0.41729634 0.25575268 0.6895114  0.14933577 0.39241937
  0.68590098 0.25738808 0.06573346 0.83699526 0.14605917 0.81176179
  0.74820536 0.06284479]
 [0.88239722 0.20887984 0.54001622 0.84549726 0.57716392 0.71891173
  0.08973337 0.3

In [16]:
x = abs(test - train)[:5,:5]; x

array([[0.00334066, 0.67017672, 0.33904034, 0.0335593 , 0.30189264],
       [0.52102246, 0.15249491, 0.17864147, 0.4841225 , 0.21578917],
       [0.91876338, 0.24524601, 0.57638239, 0.88186342, 0.61353009],
       [0.09979203, 0.57372534, 0.24258896, 0.06289207, 0.20544126],
       [0.88239722, 0.20887984, 0.54001622, 0.84549726, 0.57716392]])

In [17]:
np.trace(x)

1.3722739551354157

In [18]:
print(np.trace(abs(test - train)))

2.6326327863467744


In [19]:
y = abs(test - train).reshape(2, 5, 4, 5); print(y)

[[[[0.00334066 0.67017672 0.33904034 0.0335593  0.30189264]
   [0.16014483 0.96878993 0.51374772 0.35220406 0.78596277]
   [0.24578715 0.48887075 0.78235236 0.35383946 0.16218484]
   [0.93344664 0.24251055 0.90821317 0.84465674 0.03360659]]

  [[0.52102246 0.15249491 0.17864147 0.4841225  0.21578917]
   [0.35753697 0.45110812 0.00393409 0.16547774 0.26828097]
   [0.27189465 0.02881106 0.26467055 0.16384234 0.35549696]
   [0.41576483 0.27517126 0.39053136 0.32697493 0.48407522]]

  [[0.91876338 0.24524601 0.57638239 0.88186342 0.61353009]
   [0.75527789 0.0533672  0.40167501 0.56321867 0.12945995]
   [0.66963558 0.42655198 0.13307037 0.56158327 0.75323789]
   [0.01802391 0.67291218 0.00720956 0.07076599 0.88181614]]

  [[0.09979203 0.57372534 0.24258896 0.06289207 0.20544126]
   [0.06369346 0.87233855 0.41729634 0.25575268 0.6895114 ]
   [0.14933577 0.39241937 0.68590098 0.25738808 0.06573346]
   [0.83699526 0.14605917 0.81176179 0.74820536 0.06284479]]

  [[0.88239722 0.20887984 0.5400

In [20]:
np.trace(y, axis1=1, axis2=3)

array([[1.37227396, 1.36177444, 1.38192838, 2.80948279],
       [1.60234675, 1.26035883, 1.43465263, 2.31285557]])

In [21]:
a = abs(test - train)[:5,:5]
print(a)
print(np.trace(a))

[[0.00334066 0.67017672 0.33904034 0.0335593  0.30189264]
 [0.52102246 0.15249491 0.17864147 0.4841225  0.21578917]
 [0.91876338 0.24524601 0.57638239 0.88186342 0.61353009]
 [0.09979203 0.57372534 0.24258896 0.06289207 0.20544126]
 [0.88239722 0.20887984 0.54001622 0.84549726 0.57716392]]
1.3722739551354157


In [22]:
A = np.arange(1, 17).reshape(4, -1)

In [23]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
np.hsplit(A, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [25]:
x = abs(test - train)
np.hsplit(x, 2)

[array([[0.00334066, 0.67017672, 0.33904034, 0.0335593 , 0.30189264,
         0.16014483, 0.96878993, 0.51374772, 0.35220406, 0.78596277],
        [0.52102246, 0.15249491, 0.17864147, 0.4841225 , 0.21578917,
         0.35753697, 0.45110812, 0.00393409, 0.16547774, 0.26828097],
        [0.91876338, 0.24524601, 0.57638239, 0.88186342, 0.61353009,
         0.75527789, 0.0533672 , 0.40167501, 0.56321867, 0.12945995],
        [0.09979203, 0.57372534, 0.24258896, 0.06289207, 0.20544126,
         0.06369346, 0.87233855, 0.41729634, 0.25575268, 0.6895114 ],
        [0.88239722, 0.20887984, 0.54001622, 0.84549726, 0.57716392,
         0.71891173, 0.08973337, 0.36530884, 0.5268525 , 0.09309379],
        [0.38892798, 0.28458939, 0.04654699, 0.35202802, 0.08369469,
         0.22544249, 0.5832026 , 0.12816039, 0.03338327, 0.40037545],
        [0.39999542, 0.27352195, 0.05761443, 0.36309546, 0.09476213,
         0.23650993, 0.57213516, 0.11709295, 0.0444507 , 0.38930801],
        [0.29990893, 0.3736

In [26]:
np.trace(x)

2.6326327863467744

In [27]:
a = np.array([2, 3, 4, 1, 5])
i = np.argsort(a)[0]
a[i]

1

## numpy masks

In [28]:
a = np.arange(1, 7).reshape(2, 3)
mask = a > 3
print(a)
print()
print(mask)

[[1 2 3]
 [4 5 6]]

[[False False False]
 [ True  True  True]]


In [29]:
print(a[mask])
shiny_mask = [True, False]
print(a[shiny_mask])

[4 5 6]
[[1 2 3]]


In [1]:
'1 2 3'.split().__len__()

3