In [1]:
import numpy as np

In [48]:
train = np.random.rand(4, 5)
test = np.random.rand(2, 5)
print(train)
print()
print(test)

[[0.4908663  0.34933505 0.88179293 0.83738391 0.71276635]
 [0.80225363 0.68383455 0.031934   0.89841203 0.41005945]
 [0.52413795 0.18307383 0.61039441 0.12331373 0.90481026]
 [0.40972721 0.60124445 0.35577735 0.93299849 0.21656078]]

[[0.9716926  0.57215984 0.95986856 0.13324418 0.9621103 ]
 [0.47031615 0.33078857 0.6002458  0.9537787  0.59063879]]


In [65]:
train = train.reshape(1, -1)
test = test.reshape(-1, 1)

In [66]:
print(train[:5])
print()
print(test[:,:5])

[[0.4908663  0.34933505 0.88179293 0.83738391 0.71276635 0.80225363
  0.68383455 0.031934   0.89841203 0.41005945 0.52413795 0.18307383
  0.61039441 0.12331373 0.90481026 0.40972721 0.60124445 0.35577735
  0.93299849 0.21656078]]

[[0.9716926 ]
 [0.57215984]
 [0.95986856]
 [0.13324418]
 [0.9621103 ]
 [0.47031615]
 [0.33078857]
 [0.6002458 ]
 [0.9537787 ]
 [0.59063879]]


In [67]:
print(abs(test - train))

[[0.48082629 0.62235755 0.08989967 0.13430869 0.25892625 0.16943896
  0.28785805 0.9397586  0.07328057 0.56163315 0.44755465 0.78861877
  0.36129819 0.84837887 0.06688234 0.56196539 0.37044815 0.61591525
  0.03869411 0.75513182]
 [0.08129354 0.22282479 0.30963309 0.26522407 0.14060651 0.23009379
  0.11167471 0.54022585 0.32625218 0.16210039 0.04802189 0.38908601
  0.03823457 0.44884611 0.33265041 0.16243263 0.02908461 0.21638249
  0.36083865 0.35559906]
 [0.46900225 0.6105335  0.07807563 0.12248465 0.2471022  0.15761492
  0.27603401 0.92793456 0.06145653 0.54980911 0.4357306  0.77679473
  0.34947415 0.83655483 0.0550583  0.55014135 0.3586241  0.6040912
  0.02687007 0.74330778]
 [0.35762213 0.21609087 0.74854875 0.70413973 0.57952217 0.66900945
  0.55059037 0.10131018 0.76516785 0.27681527 0.39089377 0.04982965
  0.47715023 0.00993045 0.77156608 0.27648303 0.46800027 0.22253317
  0.79975431 0.0833166 ]
 [0.47124399 0.61277525 0.08031737 0.12472639 0.24934395 0.15985667
  0.27827575 0.93

In [88]:
x = abs(test - train)[:5,:5]; x

array([[0.48082629, 0.62235755, 0.08989967, 0.13430869, 0.25892625],
       [0.08129354, 0.22282479, 0.30963309, 0.26522407, 0.14060651],
       [0.46900225, 0.6105335 , 0.07807563, 0.12248465, 0.2471022 ],
       [0.35762213, 0.21609087, 0.74854875, 0.70413973, 0.57952217],
       [0.47124399, 0.61277525, 0.08031737, 0.12472639, 0.24934395]])

In [89]:
np.trace(x)

1.7352103869051936

In [93]:
print(np.trace(abs(test - train)))

3.2244516667956744


In [92]:
y = abs(test - train).reshape(2, 5, 4, 5); print(y)

[[[[0.48082629 0.62235755 0.08989967 0.13430869 0.25892625]
   [0.16943896 0.28785805 0.9397586  0.07328057 0.56163315]
   [0.44755465 0.78861877 0.36129819 0.84837887 0.06688234]
   [0.56196539 0.37044815 0.61591525 0.03869411 0.75513182]]

  [[0.08129354 0.22282479 0.30963309 0.26522407 0.14060651]
   [0.23009379 0.11167471 0.54022585 0.32625218 0.16210039]
   [0.04802189 0.38908601 0.03823457 0.44884611 0.33265041]
   [0.16243263 0.02908461 0.21638249 0.36083865 0.35559906]]

  [[0.46900225 0.6105335  0.07807563 0.12248465 0.2471022 ]
   [0.15761492 0.27603401 0.92793456 0.06145653 0.54980911]
   [0.4357306  0.77679473 0.34947415 0.83655483 0.0550583 ]
   [0.55014135 0.3586241  0.6040912  0.02687007 0.74330778]]

  [[0.35762213 0.21609087 0.74854875 0.70413973 0.57952217]
   [0.66900945 0.55059037 0.10131018 0.76516785 0.27681527]
   [0.39089377 0.04982965 0.47715023 0.00993045 0.77156608]
   [0.27648303 0.46800027 0.22253317 0.79975431 0.0833166 ]]

  [[0.47124399 0.61277525 0.0803

In [100]:
np.trace(y, axis1=1, axis2=3)

array([[1.73521039, 2.52626693, 1.2533453 , 2.74044503],
       [0.55916613, 1.48924128, 1.3563216 , 0.97037149]])

# ПОБЕДА

In [52]:
a = abs(test - train)[:5,:5]
print(a)
print(np.trace(a))

[[0.48082629 0.08129354 0.46900225 0.35762213 0.47124399]
 [0.62235755 0.22282479 0.6105335  0.21609087 0.61277525]
 [0.08989967 0.30963309 0.07807563 0.74854875 0.08031737]
 [0.13430869 0.26522407 0.12248465 0.70413973 0.12472639]
 [0.25892625 0.14060651 0.2471022  0.57952217 0.24934395]]
1.7352103869051936


In [25]:
A = np.arange(1, 17).reshape(4, -1)

In [26]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
np.split(A, [:2, :2])

SyntaxError: invalid syntax (<ipython-input-38-91fde5434b5b>, line 1)

In [37]:
np.trace(b)

array([[14, 16],
       [18, 20]])

In [40]:
np.hsplit(A, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [42]:
x = abs(test - train)
np.hsplit(x, 2)

[array([[0.13103703, 0.18627341, 0.45940561, 0.44939251, 0.3075609 ],
        [0.64471114, 0.3274007 , 0.0542685 , 0.0642816 , 0.20611321],
        [0.95298506, 0.63567461, 0.36254242, 0.37255551, 0.51438712],
        [0.11813473, 0.19917571, 0.47230791, 0.46229481, 0.3204632 ],
        [0.95768091, 0.64037047, 0.36723828, 0.37725137, 0.51908298],
        [0.83856143, 0.52125099, 0.24811879, 0.25813189, 0.3999635 ],
        [0.99325695, 0.6759465 , 0.40281431, 0.41282741, 0.55465902],
        [0.71571664, 0.3984062 , 0.12527401, 0.1352871 , 0.27711871],
        [0.17429643, 0.14301402, 0.41614621, 0.40613312, 0.26430151],
        [0.4803568 , 0.16304635, 0.11008584, 0.10007275, 0.04175886],
        [0.3827975 , 0.06548705, 0.20764514, 0.19763205, 0.05580044],
        [0.29409446, 0.02321599, 0.29634818, 0.28633508, 0.14450347],
        [0.00644647, 0.31086397, 0.58399617, 0.57398307, 0.43215146],
        [0.02141746, 0.29589299, 0.56902518, 0.55901209, 0.41718047],
        [0.75648201,

In [32]:
np.trace(x)

array([[0.92043757, 0.60621981, 0.74120095, 0.60075742, 0.7258952 ],
       [0.68622744, 0.59124882, 0.72622996, 0.58578643, 0.71092421],
       [1.41914069, 0.7323761 , 0.32109286, 0.20067551, 0.60947652],
       [0.90761787, 0.65748983, 0.5225087 , 0.66295223, 0.53781444],
       [0.99235006, 0.96576375, 0.83078261, 0.97122614, 0.84608836]])